name: Deploy VPC & Subnet

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - dev
          - qa

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
  TF_WORK_DIR: terraform/${{ github.event.inputs.environment }}

steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Set AWS Credentials (Dev)
    if: ${{ github.event.inputs.environment == 'dev' }}
    run: |
      echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_ENV
      echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_ENV

  - name: Set AWS Credentials (QA)
    if: ${{ github.event.inputs.environment == 'qa' }}
    run: |
      echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_QA }}" >> $GITHUB_ENV
      echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}" >> $GITHUB_ENV

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: 1.8.5

  - name: Terraform Init
    run: terraform init
    working-directory: ${{ env.TF_WORK_DIR }}

  - name: Terraform Plan
    run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"
    working-directory: ${{ env.TF_WORK_DIR }}

  - name: Terraform Apply
    run: terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
    working-directory: ${{ env.TF_WORK_DIR }}

