name: Terraform VPC Deployment

on:
  push:
    branches:
      - dev
      - qa
  workflow_dispatch:   

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment
        id: envselect
        run: |
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "qa" ]]; then
            echo "env=qa" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" != "" ]]; then
            echo "env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=terraform/environment/${{ steps.envselect.outputs.env }} init

      - name: Terraform Plan
        run: terraform -chdir=terraform/environment/${{ steps.envselect.outputs.env }} plan

      - name: Terraform Apply
        run: terraform -chdir=terraform/environment/${{ steps.envselect.outputs.env }} apply -auto-approve
