name: Deploy VPC and Subnet

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environments:"
        required: true
        type: choice
        default: "none"
        options:
          - "dev"
          - "qa"

jobs:
  Create-Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Debug - List Folders
        run: ls -R

      - name: Export AWS Credentials 
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environment/${{ github.event.inputs.environment }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/environment/${{ github.event.inputs.environment }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/environment/${{ github.event.inputs.environment }}
